#! /bin/sh

pgrep -x sxhkd >/dev/null || sxhkd &

bspc monitor -d '1' '2' '3' '4' '5' '6' '7' '8' '9' '10' '11' '12'

bspc config border_width 0
bspc config focused_border_color "#c7b198"
bspc config normal_border_color "#09090F"
bspc config window_gap 10
bspc config top_padding 33
bspc config bottom_padding 0
bspc config left_padding 0
bspc config right_padding 0
bspc config pointer_modifier mod1
bspc config pointer_motion_interval 7ms
bspc config ignore_ewmh_focus true
bspc config external_rules_command ~/.config/bspwm/external_rules/move_windows_to_cursor.sh
bspc config split_ratio 0.52
bspc config borderless_monocle true
bspc config gapless_monocle true
bspc config focus_follows_pointer true
bspc rule -a Polybar layer=below
bspc rule -a 'Alacritty' state=floating follow=on focus=on center=false rectangle=500x300
bspc rule -a 'Spotify' desktop='10'
bspc rule -a 'vesktop' desktop='11'
bspc rule -a 'firefox' desktop='12'

#Autostart
feh --bg-scale ~/.config/bspwm/wallpapers/balcony.jpg &
setxkbmap -option caps:none &
setxkbmap -rules evdev -model evdev -layout us -variant altgr-intl &
spotify &
firefox &
sxhkd &
polybar &
picom --animations -b &
solaar --window=hide &
vesktop &
